name: Bug Report
description: Report a bug you found while using PocketPaw
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the fields below so we can reproduce and fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect instead?
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can someone else hit this bug?
      placeholder: |
        1. Run `uv run pocketpaw`
        2. Open the dashboard
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Logs
      description: Paste any error messages, stack traces, or screenshots.
      render: shell
    validations:
      required: false

  - type: input
    id: pocketpaw-version
    attributes:
      label: PocketPaw Version
      description: Output of `pocketpaw --version` or `pocketpaw --doctor`
      placeholder: "e.g., 0.4.2"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 15.2, Ubuntu 24.04, Windows 11"
    validations:
      required: false

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - pip install pocketpaw
        - uv sync (from source)
        - Docker
        - Other
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
